# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-K9b_dPzOh_A0sts-kw1TYXTmtGXUY17
"""

from IPython.display import display, HTML

html_code = """
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>StudyMate Login</title>
  <style>
    body {
      background-color:#e48afd;
      background-size: cover;
      background-repeat: no-repeat;
      background-position: center;
      margin: 0; padding: 0;
      height: 100vh;
      display: flex; justify-content: center; align-items: center;
      font-family: Verdana, Geneva, Tahoma, sans-serif;
    }
    .login-container { width: 100%; max-width: 420px; }
    .regform {
      background-color: black; padding: 30px;
      border-radius: 12px; color: white; text-align: center;
      box-shadow: 0px 4px 15px rgba(0,0,0,0.5);
    }
    .regform h2 { margin: 0; color: #00bcd4; }
    .regform h3 { margin: 10px 0 20px; color: #e29578; }
    .textlabel { display: block; text-align: left; margin: 10px 0 5px; font-size: 16px; }
    .regform input[type="text"], .regform input[type="password"] {
      width: 100%; padding: 10px; margin-bottom: 15px;
      font-size: 1em; border: 2px solid #006077;
      border-radius: 6px; outline: none;
      box-shadow: inset 1px 1px 4px rgba(0,0,0,0.3);
    }
    .regform input:focus {
      background-color: #53b1a7; border-color: #0793a6;
      box-shadow: 0px 0px 8px #069fb3;
    }
    .gender { display: flex; justify-content: space-around; margin: 15px 0; }
    .options { display: flex; justify-content: space-between; align-items: center; margin: 10px 0 20px; }
    .options a { color: #00bcd4; text-decoration: none; font-size: 14px; }
    .options a:hover { text-decoration: underline; }
    .regform button {
      width: 100%; padding: 12px; font-size: 1em;
      background: #006077; color: white; border: none; border-radius: 6px;
      cursor: pointer; transition: background 0.3s ease;
    }
    .regform button:hover { background: #004c5c; }
    .signup-text { margin-top: 15px; font-size: 14px; }
    .signup-text a { color: #00bcd4; text-decoration: none; }
    .signup-text a:hover { text-decoration: underline; }
  </style>
</head>
<body>
  <div class="login-container">
    <div class="regform">
      <h2>StudyMate</h2>
      <h3>Login</h3>
      <form action="https://189c6b3bfe750c21e1.gradio.live" method="get" target="_blank">
        <label class="textlabel" for="username">Username</label>
        <input type="text" id="username" name="username" placeholder="Enter username">
        <label class="textlabel" for="password">Password</label>
        <input type="password" id="password" name="password" placeholder="Enter password">
        <div class="gender">
          <label><input type="radio" name="gender" value="male"> Male</label>
          <label><input type="radio" name="gender" value="female"> Female</label>
        </div>
        <div class="options">
          <label><input type="checkbox"> Remember me</label>
          <a href="#">Forgot password?</a>
        </div>
        <button type="submit">Login</button>
        <p class="signup-text">Don't have an account? <a href="#">Sign up</a></p>
      </form>
    </div>
  </div>
</body>
</html>
"""

display(HTML(html_code))